### ISSUE TITLE
Lao.traineddata and lao.traineddata names conflict on macOS filesystem

### ISSUE THREAD

**Issue by willfrey** [tesseract-ocr/tessdata_best#10]
MacOS filesystem is case insensitive (annoying, I know), so only one of the `{Lao,lao}.traineddata` files ends up getting downloaded/cloned.

This is also a problem with [tesseract-ocr/tessdata_fast](https://github.com/tesseract-ocr/tessdata_fast). I can open a separate issue there and reference this issue, if you'd like.

I don't know how many Mac users will find themselves wanting to perform OCR on Lao text but I thought I'd bring up the naming conflict issue.

Thanks!

**Comment by amitdo** [comment]
A workaround:

You can first download 'Lao.traineddata' and change its name to 'Lao_.traineddata' or 'Lao_Eng.traineddata' and then download 'lao.traineddata'.

**Comment by stweil** [comment]
Pull request #21 addresses this issue.

**Comment by stweil** [comment]
@willfrey, this issue is fixed now.

**Comment by Shreeshrii** [comment]
@zdenop  Please close the issue.
