### ISSUE TITLE
Failed loading language 'Armenian' and 'hye'

### ISSUE THREAD

**Issue by axper** [tesseract-ocr/tessdata_best#13]
My tesseract version:
```
tesseract 3.05.01
 leptonica-1.74.4
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.5.1) : libpng 1.6.34 : libtiff 4.0.8 : zlib 1.2.11 : libwebp 0.6.0
```
I have put the `Armenian.traineddata` and `hye.traineddata` from this repo in `/usr/share/tessdata`.
Running the following commands:

```
$ tesseract whatever.jpg whatever.out -l Armenian
Failed loading language 'Armenian'
Tesseract couldn't load any languages!
```
```
$ tesseract whatever.jpg whatever.out -l hye
Failed loading language 'hye'
Tesseract couldn't load any languages!
```
Tell me if you need any more info to fix this.

**Comment by amitdo** [comment]
Those traineddata files only compatible with version 4.0.

**Comment by axper** [comment]
@amitdo Hmm downgraded tesseract to:
```
tesseract 3.04.01
 leptonica-1.74.4
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.5.1) : libpng 1.6.34 : libtiff 4.0.8 : zlib 1.2.11 : libwebp 0.6.0
```
And still getting the same error.
Also how can I build the traineddata files for latest version?

**Comment by amitdo** [comment]
I said version 4.0, not 3.04.01.

 3.0x does not have traineddata for Armenian.

To use the traineddata files in this repo, you need the latest code from tesseract master branch.

**Comment by axper** [comment]
Yep 4.0 worked for me, though various font recognition for Armenian is far from perfect.
