### ISSUE TITLE
can you recommend the best traineddata for numbers and latin letters

### ISSUE THREAD

**Issue by JenyaKirmizaTripTop** [tesseract-ocr/tessdata_best#18]
I'm using tesseract for reading mrz codes and sometimes it gives me incorrect symbols eg. instead of "I" it gives me "1" or instead of "5" it gives "S"

**Comment by Shreeshrii** [comment]
Which version of tesseract and traineddata are you using?

**Comment by JenyaKirmizaTripTop** [comment]
I'm using tess2 and i want to select which traindata will fit bettter cause i need to read from MRZ passport  code, and it has such symbols '<,>', numbers and alpha letters 
I see some mistakes while reading <,> and also while reading alpha letters

**Comment by Shreeshrii** [comment]
You may get better response to such questions on the tesseract-ocr forum. 

Or open an issue on for tesseract.

You can also search for mrz.traineddata, it won't be in official repo but user contribution

**Comment by Shreeshrii** [comment]
See https://github.com/tesseract-ocr/tesseract/wiki/AddOns
