### ISSUE TITLE
What's the difference between 'chi_sim.traineddata' and 'chi_sim_vert.traineddata'?

### ISSUE THREAD

**Issue by toxic-0518** [tesseract-ocr/tessdata_best#20]
In tesseract-ocr/tessdata_best folder,there are two models related to Simplified Chinese, called 'chi_sim.traineddata' and 'chi_sim_vert.traineddata'.

I wonder what's the difference between them, thanks!

**Comment by Shreeshrii** [comment]
Please see
https://github.com/tesseract-ocr/tessdata_fast/blob/master/README.md

Read the last section re jpn_vert

Same applies for chi_sim_vert

**Comment by toxic-0518** [comment]
Thank you for your answer!
I'll close this issue.
