### ISSUE TITLE
 Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again

### ISSUE THREAD

**Issue by leisoneduardo** [tesseract-ocr/tessdata_best#29]
Hello friends,
I have a big problem, and I researched elsewhere there is an answer option when I run my project to read files with the PDF extension after it has been found.

You have done some procedures like the bug itself -> "ulimit -c unlimited" before starting Java again
but it did not help at all, can anyone help me?

Hugs;

contains_unichar_id(unichar_id):Error:Assert failed:in file ../../src/ccutil/unicharset.h, line 511
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f5e3fe4d3ca, pid=26196, tid=0x00007f5e422e2700
#
# JRE version: Java(TM) SE Runtime Environment (8.0_171-b11) (build 1.8.0_171-b11)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.171-b11 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libtesseract.so+0x2b13ca]  ERRCODE::error(char const*, TessErrorLogCode, char const*, ...) const+0x16a
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /root/_Leitor/hs_err_pid26196.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
Aborted

**Comment by zdenop** [comment]
We do not provide support for 3rd projects.
