### ISSUE TITLE
Failed loading language 'eng'

### ISSUE THREAD

**Issue by kakadiyahardik** [tesseract-ocr/tessdata_best#30]
I installed tesseract-ocr (tesseract 3.04.01) in Ubuntu and it's work fine, but i want to use best traineddata
so when I changed eng.traineddata with tessdata_best eng.traineddata from `/usr/share/tesseract-ocr/tessdata/eng.traineddata` path it's gives below error

`hardik@hardik-HP-Laptop-15-bs1xx:~$ tesseract /home/hardik/Downloads/test.jpg stdout`
 `Failed loading language 'eng'`
`Tesseract couldn't load any languages!`
`Could not initialize tesseract.`

**Comment by zdenop** [comment]
You can not use tesseract 4 data with tesseract 3
