### ISSUE TITLE
request to add new fonts for Telugu language

### ISSUE THREAD

**Issue by pikeview** [tesseract-ocr/tessdata_best#31]
Hi,
There are 18 free unicode Telugu fonts available at http://fonts.siliconandhra.org/
Can this be included in the training data please?

regards

**Comment by Shreeshrii** [comment]
These are the fonts used for LSTM training

https://github.com/tesseract-ocr/langdata_lstm/blob/master/tel/okfonts.txt

**Comment by pikeview** [comment]
Tq.. the fonts I mentioned are already there
