### ISSUE TITLE
Fail to load standalone number or some words in Vietnamese

### ISSUE THREAD

**Issue by YuiyuD** [tesseract-ocr/tessdata_best#38]
Tested with vie.traineddata, they returned null, ("")
![word](https://i.imgur.com/3Rcd2ff.png)
![word](https://i.imgur.com/lhMJsCp.png)
![num](https://i.imgur.com/hylX9bo.png)
![num](https://i.imgur.com/FhsQb5R.png)
![num](https://i.imgur.com/exbKNPv.png)

can we have any way to improve them? Thank you so much!

**Comment by zdenop** [comment]
Please use tesseract user forum for asking support
