### ISSUE TITLE
Source of scripts/Fraktur etc.

### ISSUE THREAD

**Issue by mikegerber** [tesseract-ocr/tessdata_best#39]
While the files in the top directory seem to come from the sources in the [langdata](https://github.com/tesseract-ocr/langdata) repository, the source for some of the files in `scripts/` is unclear:

* `scripts/Fraktur.traineddata` has no matching file in langdata,
* `scripts/Japanese.traineddata` also, etc.

The [Data-Files](https://github.com/tesseract-ocr/tesseract/wiki/Data-Files) wiki article does not mention `scripts/Fraktur`.

This adds to the confusion of the `frk` language (not actually frankish, but Fraktur), the `Fraktur` script and the legacy model `deu_frak` in the tessdata repository.

**Comment by Shreeshrii** [comment]
See

https://github.com/tesseract-ocr/tessdata_fast/blob/master/README.md

https://github.com/tesseract-ocr/langdata_lstm/blob/master/script/Fraktur.langs.txt

**Comment by Shreeshrii** [comment]
Also see https://github.com/tesseract-ocr/tessdata/issues/65

**Comment by mikegerber** [comment]
Is langdata obsolete as langdata_lstm exists?

**Comment by Shreeshrii** [comment]
langdata files are appropriate for tesseract 3 or for legacy/base versions using tesseract 4. They can also be used for finetuning which requires a smaller input training text.

**Comment by stweil** [comment]
As @Shreeshrii already said, `langdata_lstm` is for LSTM models while `langdata` is for legacy models. Both kinds of models are still used.

The `script`models are mixtures of different languages. `script/Fraktur` for example combines [enm+frm+frk+ita_old+spa_old](https://github.com/tesseract-ocr/langdata_lstm/blob/master/script/Fraktur.langs.txt).

I fixed the description for 4.00 `frk` in the Wiki. The other Wiki issues are still open.

**Comment by Akossimon** [comment]
Fraktur Tesseract OCR is what I am looking for,.... I installed VietOCR and Tesseract 4.01 on my mac, but I am trying to find help on how to train it better.... thee are too many errors... how would I go about training the software? Can anyone help?

**Comment by stweil** [comment]
In the meantime [newer Fraktur models](https://ub-backup.bib.uni-mannheim.de/~stweil/ocrd-train/data/Fraktur_5000000/) are available. There is a [description of the training process](https://github.com/tesseract-ocr/tesstrain/wiki/GT4HistOCR) for those models in the Wiki.

As soon as the training is finished, I'll add the results to [tessdata_contrib](https://github.com/tesseract-ocr/tessdata_contrib).

**Comment by stweil** [comment]
@mikegerber, can we close this issue?
