### ISSUE TITLE
Feedback Latin.traineddata

### ISSUE THREAD

**Issue by TheSeiko** [tesseract-ocr/tessdata_best#4]
All Errors are in comparison to the old Latin.traineddata:
https://github.com/tesseract-ocr/tessdata/issues/82

Compiled 13.09.2017 tesseract Windows 10 x86

---

Recognition Error A -> Ä

![1454419179964_2](https://user-images.githubusercontent.com/30631253/30548780-57e42274-9c93-11e7-868f-bad2bb3e3c36.jpg)
[1454419179964_2.txt.txt](https://github.com/tesseract-ocr/tessdata_best/files/1311117/1454419179964_2.txt.txt)

**Comment by TheSeiko** [comment]
Problems with E/F at begin of line
Often "E" is recognised as "F"

![1454436670744_subimage](https://user-images.githubusercontent.com/30631253/30550047-a760519e-9c96-11e7-985f-8d08364d877a.png)
[1454436670744_subImage.txt](https://github.com/tesseract-ocr/tessdata_best/files/1311193/1454436670744_subImage.txt)

**Comment by TheSeiko** [comment]
E/F

![1454438383366_subimage](https://user-images.githubusercontent.com/30631253/30550223-17c5b866-9c97-11e7-88c6-c2748ceeea21.png)
[1454438383366_subImage.txt](https://github.com/tesseract-ocr/tessdata_best/files/1311203/1454438383366_subImage.txt)

**Comment by TheSeiko** [comment]
small/capital letters

![1454455689122_subimage](https://user-images.githubusercontent.com/30631253/30550354-7d787cde-9c97-11e7-98cb-553c070f9b6e.png)
[1454455689122_subImage.txt](https://github.com/tesseract-ocr/tessdata_best/files/1311213/1454455689122_subImage.txt)

**Comment by TheSeiko** [comment]
When a sentence spans multiple lines and the only one or two words are in the last line, the words in last line are often recognised with capital letters. 
Here: Wird
Expected: wird

![1511823574752_subimage](https://user-images.githubusercontent.com/30631253/33317147-a18751e6-d436-11e7-9de5-3af5d0fb5b36.png)

**Comment by stweil** [comment]
I just tried all of the examples above with Tesseract 5.3.1 and tessdata_fast/script/Latin. Most of them were recognized perfectly. I only got one Ä/A and one ß/B confusion.
