### ISSUE TITLE
fra.traineddata corrupted ?

### ISSUE THREAD

**Issue by japafrite** [tesseract-ocr/tessdata_best#42]
Hey, this fra.traineddata (in tessdata_best) doesn't work, I get this error:
pytesseract.pytesseract.TesseractError: (1, "Tesseract Open Source OCR Engine v3.04.01 with Leptonica read_params_file: Can't open 1 read_params_file: Can't open -psm read_params_file: Can't open 7 Failed loading language 'fra' Tesseract couldn't load any languages! Could not initialize tesseract.")
And this file seems to small compared to others.
Everything works when I come back to original file.

**Comment by stweil** [comment]
Chances are high that you did not download the traineddata file, but a HTML page. Try to open the file in your editor.

**Comment by japafrite** [comment]
My editor can't open it because it's not a text file or encoding is not supported.
Method applied : download button with firefox and then move file
fra.traineddata 4.0 on https://github.com/tesseract-ocr/tesseract/wiki/Data-Files => OK
fra.traineddata on https://github.com/tesseract-ocr/tessdata => OK
fra.traineddata on https://github.com/tesseract-ocr/tessdata_best => NOK

**Comment by zdenop** [comment]
Your tesseract (version) is old you download datafiles for recent version which of course does not work (expected behavior). Upgrade your tesseract and everything will works.
