### ISSUE TITLE
Digit mixed up

### ISSUE THREAD

**Issue by NiHoel** [tesseract-ocr/tessdata_best#43]
## Setup
Tesseract Version:
Tesseract 64 bits version:
tesseract v4.0.0-1
leptonica-1.76.0
libjpeg-turbo 2.0.1-1 : libpng 1.6.7-14 : libtiff 4.0.10-4 : zlib 1.2.11-5

Platform:
Windows 10 64 bits

## Input
![pop_houses_text](https://user-images.githubusercontent.com/28017252/70849328-3bb9d080-1e7d-11ea-9cb9-e80b61b7e0c2.png)

PageSegMode::PSM_SINGLE_LINE
language: German

## Output
142

## Expected output
112

**Comment by zdenop** [comment]
```sh
tesseract unnamed.png - --psm 7
Warning: Invalid resolution 0 dpi. Using 70 instead.
112
```

```
tesseract -v
tesseract 5.0.0-alpha-551-g99df
 leptonica-1.79.0 (Nov 10 2019, 15:22:01) [MSC v.1916 LIB Release x64]
  libgif 5.1.2 : libjpeg 6b (libjpeg-turbo 2.0.2) : libpng 1.6.36 : libtiff 4.0.10 : zlib 1.2.11 : libwebp 1.0.2 : libopenjp2 2.3.0
 Found AVX2
 Found AVX
 Found FMA
 Found SSE
 Found libarchive 3.3.3 zlib/1.2.11 liblzma/5.2.4 libzstd/1.3.8
```

Solution: the the recent code.
