### ISSUE TITLE
"§" symbol is not recognized in German language models

### ISSUE THREAD

**Issue by Apolyxon** [tesseract-ocr/tessdata_best#45]
The "§" is not recognized and instead the "$" symbol is recognized.

In German legal texts and books the "§" symbol is ubiquitous. It is not a special character that is only needed in a few specialized cases.

**Comment by stweil** [comment]
This is a known issue and there exist already lots of reports for it. Use `script/Latin` as a workaround.

**Comment by Apolyxon** [comment]
@stweil Does this mean, it is going to be fixed? Can you provide a link to the duplicated issue?

Using script/latin is more work to correct than using the German Model and simply substituting the wrong symbol.

**Comment by stweil** [comment]
Issues which relate to the missing paragraph character:
https://github.com/tesseract-ocr/tessdata/issues?q=is%3Aissue+paragraph.

**Comment by stweil** [comment]
> Does this mean, it is going to be fixed?

Tesseract development is currently entirely driven by volunteers, so it will only be fixed if someone (you?) is sufficiently interested and has the resources to do that.

I have rather good models for historic German texts (15th to early 20th century) at https://ub-backup.bib.uni-mannheim.de/~stweil/ocrd-train/data/, but for modern German text they are less good.

**Comment by Apolyxon** [comment]
@stweil I unfortunately have no idea where to start. Probably retrain the model with sufficient data? However it seems like (looking at the duplicated thread) that the current training data already has training data with the "§" symbol. 

Does that mean you just have to regenerate the German language model with the current training data until it is sufficiently good?

**Comment by stweil** [comment]
Yes, "you just have to regenerate the German language model". The problem is that last time Ray Smith did that, and we only know vaguely how he did it.
