### ISSUE TITLE
Can't use ita.traineddata

### ISSUE THREAD

**Issue by Betacentury** [tesseract-ocr/tessdata_best#48]
While using ita.traineddata I get this error message: 

> read_params_file: parameter not found: 

I'm using tesseract 4.1 on Ubuntu 19.04

```
$ tesseract --version
tesseract 4.1.0
 leptonica-1.78.0
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 2.0.1) : libpng 1.6.37 : libtiff 4.0.10 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.3.0
 Found AVX2
 Found AVX
 Found SSE
```

**Comment by zdenop** [comment]
Please write command you used.

**Comment by Betacentury** [comment]
I found that is my fault:

My application is using a static compiled libtesseract.so.3.0.4 in place the dynamic 4.1 in my system, so I was using a non-legacy supporting trained data with an old engine.

I recently switched from tessdata to tessdata_best so I guessed the problem was with trained data, my bad.
