### ISSUE TITLE
[ISSUE]  (OSD) orientation script detection not supported using Tesseract best

### ISSUE THREAD

**Issue by davidpraise45** [tesseract-ocr/tessdata_best#57]
Hello guys, 

                    Thank you very much for supporting and making this library open source. 🙏

Currently, I noticed a few glitches while calling pytesseract.image_to_osd(image, output_type=Output.DICT) after building from source. Which should return specific meta-data about my document - like its current orientation form.

While performing my research, it complained about a missing "dict.traineddata" model. Which i have searched for and it doesn't seem to exist. 

**Error Message**
TesseractError: (1, 'Warning, detects only orientation with -l dict Error opening data file /usr/local/share/tessdata/dict.traineddata 
Please make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory.
Failed loading language \'dict\' Tesseract couldn\'t load any languages!
Could not initialize tesseract.')

Do you have any solution as to why this error occurs?

![image](https://user-images.githubusercontent.com/25937490/123970880-d1627580-d9b9-11eb-98c6-9e29eb2fba2c.png)

**Comment by stweil** [comment]
I am afraid I cannot help because this issue is related to pytesseract, not to tesseract.

**Comment by davidpraise45** [comment]
Thank you for getting back with me.
