### ISSUE TITLE
Which language file should be downloaded? 

### ISSUE THREAD

**Issue by oasaleh** [tesseract-ocr/tessdata_best#59]
Should I download the file in Script directory? or in the root? and if it is the one in Script dir, should I rename it? because all of them have the full name of the language, yet tesseract uses a 3 character input (eng instead of English). Finally, do I have to download the PDF and osd files too or just the training data?

Thank you.

**Comment by SatyamSSJ10** [comment]
idk, if I should reply now but only trainingdata or .traineddata

**Comment by stweil** [comment]
You can download language or script .traineddata files as you need. And you are free to rename your downloaded files or not.

Please use the [Tesseract user forum](https://groups.google.com/d/forum/tesseract-ocr) for additional questions.
