### ISSUE TITLE
Using tessdata_best files leads to error

### ISSUE THREAD

**Issue by qwertynik** [tesseract-ocr/tessdata_best#69]
### Description
Setup tesseract using this command on Ubuntu 20.04
```
sudo apt install tesseract-ocr
```

On realizing that tessdata_best offers better conversion, downloaded the eng and osd files from this repo and placed them here ` /usr/share/tesseract-ocr/4.00/tessdata/`. Post this, below error is thrown when using tesseract.

```
dev@ip:~/experiments$ tesseract fullImage.jpg dp
Error opening data file /usr/share/tesseract-ocr/4.00/tessdata/eng.traineddata
Please make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory.
Failed loading language 'eng'
Tesseract couldn't load any languages!
Could not initialize tesseract.
```

Ensured that the file is present with the same permissions as the file added by default.

Any ideas on how to resolve this?

### Device and package info:

**tesseract-ocr version**
```
dev@ip:~/experiments$ tesseract --version
tesseract 4.1.1
 leptonica-1.79.0
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 2.0.3) : libpng 1.6.37 : libtiff 4.1.0 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.3.1
 Found AVX512BW
 Found AVX512F
 Found AVX2
 Found AVX
 Found FMA
 Found SSE
 Found libarchive 3.4.0 zlib/1.2.11 liblzma/5.2.4 bz2lib/1.0.8 liblz4/1.9.2 libzstd/1.4.4
```

**OS Version:**
```
dev@ip:~/experiments$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal
```

**Comment by stweil** [comment]
Maybe getting the right files instead of downloading HTML helps?

Please use the [Tesseract user forum](https://groups.google.com/d/forum/tesseract-ocr) for questions.

**Comment by stweil** [comment]
Why do you think that tessdata_best would be better for you? You will only need it for training.

**Comment by qwertynik** [comment]
> Maybe getting the right files instead of downloading HTML helps?
> 
> Please use the [Tesseract user forum](https://groups.google.com/d/forum/tesseract-ocr) for questions.

@stweil 
Started experimenting more post creating this issue. Was earlier downloading the file directly from the repo. And the file size for a better trained data being lesser seemed to be off.
Post this download the package from Releases page here and got it working now.

**Comment by qwertynik** [comment]
> Why do you think that tessdata_best would be better for you? You will only need it for training.

That's interesting to know. On this [page](https://tesseract-ocr.github.io/tessdoc/Data-Files)  the accuracy level is marked the highest for tessdata_best. Had also noticed the same when experimenting with it.

Is the documentation outdated or am I missing something?
