### ISSUE TITLE
Invalid symlink makes tar fail

### ISSUE THREAD

**Issue by Mek101** [tesseract-ocr/tessdata_best#70]
I'm currently trying package the latest release in a flatpak module. However, extracting the archive fails because it contains an invalid symlink `/tessdata_best-4.1.0/config`, which points to a non-existing file. Could you remove it from the archive please?

**Comment by stweil** [comment]
The symlink is there for a good reason: in a cloned git working directory with submodule it is needed and valid. And there is also another symbolic link tessdata_best-4.1.0/pdf.ttf for the same reason.

Maybe you can use the zip download or get the data with git? I wonder whether it is useful to make a 1.7 GB large flatpak module.

**Comment by stweil** [comment]
Which tar are you using on what platform? I tried tar on Debian GNU Linux and had no problems when extracting the tar archive.

**Comment by Mek101** [comment]
I ended up solving the issue by using the .zip download. I'm on Manjaro
