### ISSUE TITLE
Update all datasets that are older than 6 years and increase accuracy of the LSTM models

### ISSUE THREAD

**Issue by urosjarc** [tesseract-ocr/tessdata_best#79]
When it comes to the opensourced product there is always
conflict of interest when they compete with paid products...

Google has Vision AI which is paid product and there is an tessaract-ocr which is opensourced product...
And as I see it google has no interest to make significant contribution to this product because of it...

What grinds my gears is that all dataset are on average 6 years old, and accuracy of the software is catastrophic.
I tried many settings and image manipulation techniques but best data models are joust failing to read simple text like they are a
small toddler trying to read a book...

The average accuracy of the models are around 75% if you apply advanced image manipulation techniques and text extraction to
serve tesseract the best data for the OCR.

# Few examples of failed OCR...

![_naslov](https://github.com/tesseract-ocr/tessdata_best/assets/8678755/007f1855-23b9-4c06-9e20-349701cf8257)
"3.1 Izjave ee ii"

![_naslov](https://github.com/tesseract-ocr/tessdata_best/assets/8678755/296a6105-c4fe-4fb9-a58d-22e6c44023da)
"2.1 Relacija deljivosti ee"

![_naslov](https://github.com/tesseract-ocr/tessdata_best/assets/8678755/6c5cd073-7cc1-4be6-94ec-554e9f7013c7)
"3.2 Množice ---M"

# Datasets all older than 6 years
![image](https://github.com/tesseract-ocr/tessdata_best/assets/8678755/f8814f11-65ed-43b9-8c60-e05b3d0b6c1f)

**Comment by stweil** [comment]
So what do you expect?

**Comment by urosjarc** [comment]
@stweil I don't know if I want to expect anything...
I went to Google Vision AI API setup order API key and got 100% accuracy on text recognition...

If google will not put some love to this repo its better to joust make this repo in to the archive state...
People come to this library with false expectation that they would get good OCR but this project joust waste
their time...

Google has a huge library of [scanned books](https://books.google.com/) on which it could provide trained data for this OCR
to increase accuracy... But why would google do that since its more occupied with their own money-making machine?

**Comment by stweil** [comment]
I'm afraid that you missed the fact that Tesseract is no longer developed by Google since a few years. The development is driven by volunteers. Anybody can contribute to the code (see [list of contributors](https://github.com/tesseract-ocr/tesseract/graphs/contributors)) or add new (or better) models (see [contributed models](https://github.com/tesseract-ocr/tessdata_contrib)). You are free to do so, too.

And many people get good OCR with Tesseract and don't think that it is a waste of their time. We use it for historic books and newspapers, and so does the Internet Archive (see [here](https://blog.archive.org/2020/11/23/foss-wins-again-free-and-open-source-communities-comes-through-on-19th-century-newspapers-and-books-and-periodicals/)).

**Comment by stweil** [comment]
One additional note: I just have run a short test, and all three examples above are recognized without any errors using the 6 years old models. Example:

```
tesseract https://user-images.githubusercontent.com/8678755/266826393-6c5cd073-7cc1-4be6-94ec-554e9f7013c7.png - -l tessdata_fast/slv
2.1 Relacija deljivosti
```

**Comment by urosjarc** [comment]
My words were directed to the company that manages this repository, if google left this repository then
I want to apologize for my inappropriate harsh words and my ignorance...

I have tried to make tesseract-ocr work for my specific case but anything I do I joust get poor accuracy

I have tried many page seq modes but the results are pretty consistent 75% - 85% accuracy. I have tried many image
manipulation techniques to help OCR recognition but everything failed

```kotlin
fun init_tessaract() {
    tesseract.setDatapath("/usr/share/tesseract-ocr/4.00/tessdata");

    tesseract.setLanguage("slv")
    tesseract.setPageSegMode(11)
    tesseract.setOcrEngineMode(1)

    tesseract.setVariable("tessedit_create_hocr", "0")
    tesseract.setVariable("user_defined_dpi", "300");
}
```

I'm trying to create searchable software for math exercises and I need to detect number of exercises and the name of the chapters...

This is one tipical example of the page that I'm dealing with...

![20230620094737_00007](https://github.com/tesseract-ocr/tessdata_best/assets/8678755/01c2a032-ae05-4714-8d87-8f343043dcbb)

With my algoritem for pixel color detection I can detect where the red character is located on the page and I can cut the image on separate peaces but when I want to get number of exercise...

I get 75% - 85% success.... And if I have 1000 exercises in the book then I need to fix 150 exercises by hand for every book that I scan and this is bad because I have 8 books in the waithing.

**Comment by stweil** [comment]
The `tesseract` executable gets most text correct without any preprocessing and with the default page segmentation mode, but fails for the mathematical expressions:
```
tesseract https://user-images.githubusercontent.com/8678755/266952073-01c2a032-ae05-4714-8d87-8f343043dcbb.jpg - -l tessdata_best/slv
1.1 Naravna števila

Množica naravnih števil: N — 11,2,9,4,...]
Osnovni računski operaciji
e seštevanje (poljubnima naravnima številoma a in b priredimo vsoto a 4 b)
e množenje (poljubnima naravnima številoma a in b priredimo produkt ab)
Osnovni računski zakoni
e zakon o zamenjavi (členov) — zakon komutativnosti za seštevanje:
arb-bta
e zakon o združevanju (členov) — zakon asociativnosti za seštevanje:
(arb) rezat bre)
e zakon o zamenjavi (faktorjev) — zakon komutativnosti za množenje:
a-bebra
e zakon o združevanju (faktorjev) — zakon asociativnosti za množenje:
(a-b) -eza-(b-e)
e zakon o razčlenjevanju — zakon distributivnosti:
a:(bre) za :bra:e
Večkratnik števila a:

nazarar...ta
pr

nčlenov

1. Izračunaj na najkrajši način:

a) 14427436 443 b) 5148244918

c) 123 4- 456 4 544 4 877 d) 2357 -4- 6944-1643 4- 306
2. Izračunaj na najkrajši način:

a) 5:29.2 b) 4-31:25

c) 4.8-25.125 d) 2-11-25-40-50
3. Izračunaj:

a) 4.743 b) 1746-12

c) 1F11:-7412 d) 2-745-3

e) 321444.3 £) 2145)43

g) 943(743) h) 3 1244144)45

i) 14-44 2(349)48 j) (3481447)

6 1. Naravna in cela števila
```

It looks like Ray Smith did not use much training material with mathematical expressions when he trained the existing models. I think that it will be possible to get good results for the formulas as well with some additional training (based on the existing model from tessdata_best). The legacy OCR engine performs much better for those parts:

```
tesseract https://user-images.githubusercontent.com/8678755/266952073-01c2a032-ae05-4714-8d87-8f343043dcbb.jpg - -l tessdata/slv --oem 0
1.1 Naravna števila

Množica naravnih števil: IN }= {1, 2, 3,4, . . .}
Osnovni računski operaciji
o' seštevanje (p-oljubnima naravnima številoma a in b priredimo vsoto a + b)
. množenje (poljubnima naravnima številoma a in b priredimo produkt a - b)
Osnovni računski zakoni
. zakon o zamenjavi (členov) — zakon komutativnosti za seštevanje:
a+b=b+a
. zakon o združevanju (členov) — zakon asociativnosti za seštevanje:
(a+b)+c:a+(b+c)
. zakon o zamenjavi (faktorjev) — zakon komutativnosti za množenje:
a - b = b - a .
. zakon o združevanju (faktorjev) — zakon asociativnosti za množenje:
(a,-b)—c:a-(b-c) '
. zakon o razčlenjevanju — zakon distributivnosti:
a-(b+c) :a-b+a—c
Večkratnik števila (1:

naza+a+...+a
\—v-—/

11 členov

1. Izračunaj na najkrajši način:

a) 14+27+36+43 b) 51+82+49+18

c) 123+456+544+877 d) 2357+694+1643+306
2. Izračunaj na najkrajši način:

a) 5-29.2 b) 4—31-25

c) 4-8-25—125 d) 2.11-25—40-50
3. Izračunaj:

a) 4-7+3 b) 17+6-12

c)1+11-7+12 d) 2-7+5-3

e) 3.214—44-3 - f) 2(1+5)+3

g) 9+3(7+3) h) 3—12+4(1+4)+5

i) 14-4+2(3+9)+8 j) (3+8)(4+7)

6 1. Naravna in cela Števila
```

**Comment by urosjarc** [comment]
The mathematical equation is not a problem, I would be happy if I got good recognition on the exercises numbers,
I will compile all the cases where tesseract failed me... It will take me a few hours...
