### ISSUE TITLE
crash when use tesseract 4 from cocoapod

### ISSUE THREAD

**Issue by saly2310** [tesseract-ocr/tessdata_best#8]

**Comment by saly2310** [comment]
actual_tessdata_num_entries_ <= TESSDATA_NUM_ENTRIES:Error:Assert failed:in file tessdatamanager.cpp, line 53

**Comment by amitdo** [comment]
https://github.com/tesseract-ocr/tesseract/wiki/FAQ#actual_tessdata_num_entries_-tessdata_num_entrieserrorassert-failedin-file-ccutiltessdatamanagercpp-line-55_

**Comment by Shreeshrii** [comment]
Are you sure you have right version of traineddata file and are using
correct --oem

**Comment by Shreeshrii** [comment]
@zdenop  Please close this issue.
