### ISSUE TITLE
Two different trained data files for greek language

### ISSUE THREAD

**Issue by VasLem** [tesseract-ocr/tessdata_best#9]
Scanning the provided trained data files, I see two data files in each different category of '_best' and '_fast', one starting with 'greek' and one starting with 'ell', with different sizes. Can someone point me to the 'best' data file to use? Thank you!

**Comment by amitdo** [comment]
The 'eli' is only for Greek, while 'Greek' was also trained for English.

Even if you need just Greek without English, I suggest to try them both and compare the result yourself.

**Comment by amitdo** [comment]
Similar issue: #6
